#!/usr/bin/env python3.10

import os
import sys
import json
import hashlib
import urllib.parse
import random
import string

from base64 import b64encode
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes


global dir_list, file_counter, dir_counter, encrypt_dir_name, encrypt_file_name
# Options
# Which File/Directory?
Name = None
# other options
encrypt_dir_name = None
encrypt_file_name = None
no_questions = None

file_counter = 0
dir_list = []

def ask(question, default):
    input1 = input(question)
    if(input1 == '' or input1 == None):
        input1 = default
    if(input1 == 'n' or input1 == 'N'):
        return False
    elif(input1 == 'y' or input1 == 'Y'):
        return True
    else:
        return ask(question, default)


for i in range(0, len(sys.argv) - 1):
    i += 1
    if(sys.argv[i] =='-h' or sys.argv[i] == '--help'):
        print('\nencrypt [Option] \n\nOptions:')
        print('-h / --help            -> shows this')
        print('DIRECTORY / FILENAME   -> encrypts this file/directory')
        print('-fn / --filenames      -> encrypts filenames too')
        print('-dn / --directorynames -> encrypts directorynames too')
        print('-nq / --no-questions   -> does not ask any questions')

        print('\nHow it works:')
        print('This script will hash ur passwd with sha256.')
        print('Then it will encrypt ur file with AES256, CBC mode.')
        print('Directories wont be compressed, it will encrypt all the files\nit contains with a recursive loop.')
        print('The key will be the hashed passwd.')
        print('The iv will be stored, like the ciphertext, in json format \nin the file.')
        print('U can decrypt the file or the directory with the command "decrypt".')
        exit()
    elif(sys.argv[i] == '-fn' or sys.argv[i] == '--filenames'):
        encrypt_file_name = True
    elif(sys.argv[i] == '-dn' or sys.argv[i] == '--directorynames'):
        encrypt_dir_name = True
    elif(sys.argv[i] == '-nq' or sys.argv[i] == '--no-questions'):
        no_questions = True
    else:
        Name = sys.argv[i]

if(Name == None):
    Name = input('File or Directory: ')
if(encrypt_file_name == None and no_questions == None):
    encrypt_file_name = ask('Encrypt filenames? [y/N] ', 'n')
if(encrypt_dir_name == None and no_questions == None):
    encrypt_dir_name = ask('Encrypt directorynames? [y/N] ', 'n')

print('U are going to encrypt: ' + Name)

key = hashlib.sha256(input('Passwd: ').encode()).digest()

def encrypt(msg):
    cipher = AES.new(key, AES.MODE_CBC)
    ct_bytes = cipher.encrypt(pad(msg, AES.block_size))
    iv = b64encode(cipher.iv).decode('utf-8')
    cipher_text = b64encode(ct_bytes).decode('utf-8')
    return [iv, cipher_text]

def encrypt_file(name, path):
    try:
        file = open(path, 'r')
        msg = bytes(file.read().encode())
        file.close()
    except Exception:
        file = open(path, 'rb')
        msg = file.read()
        file.close()
    
    content = encrypt(msg)

    if(encrypt_file_name):
        file_name = encrypt(bytes(name.encode()))
        result = json.dumps({'iv':content[0], 'ciphertext':content[1], 'name_iv':file_name[0], 'name_ciphertext':file_name[1], 'type':"file"})
    else:
        result = json.dumps({'iv':content[0], 'ciphertext':content[1], 'type':"file"})

    # Write encrypted stuff into the File
    file = open(path, 'w')
    file.write(result)
    file.close()

    if(encrypt_file_name):
        # subsitude name with random string
        # 1. make sure it does only replace the name, not other dirs
        random_name = "".join(random.choice(string.ascii_letters) for x in range(20))
        reversed_path = "".join(reversed(path))
        reversed_name = "".join(reversed(path))
        new_reversed_path = reversed_path.replace(reversed_name, random_name, 1)
        new_path = "".join(reversed(new_reversed_path))

        os.rename(path, new_path)

    return

def recursive_encryption(name, path):
    global file_counter, dir_list
    path = str(path) + str("/") + str(name)
    if(os.path.isfile(path)):
        file_counter += 1
        encrypt_file(name, path)
    elif(os.path.isdir(path)):
        dir_list.append([name, path])
        for i in os.listdir(path):
            recursive_encryption(i, path)
    else:
        print("Error: " + path)
    return

def directory_encryption():
    # why not from 0 to len(...)
    # -> start with the deepest paths
    #    otherwise paths will change
    for i in range(-len(dir_list), 0):
        real_i = -i - 1

        print('Encrypting directorynames ... ' + "{}".format(real_i+1) + ' left')

        data = encrypt(bytes(dir_list[real_i][0].encode()))

        # subsitude name with random string
        # 1. make sure it does only replace the name, not other dirs
        random_name = "".join(random.choice(string.ascii_letters) for x in range(20))
        reversed_path = "".join(reversed(dir_list[real_i][1]))
        reversed_name = "".join(reversed(dir_list[real_i][0]))
        new_reversed_path = reversed_path.replace(reversed_name, "".join(reversed(random_name)), 1)
        new_path = "".join(reversed(new_reversed_path))

        # save the encrypted name
        filename = dir_list[real_i][1] + "/" + random_name
        try:
            dir_name_file = open(filename, 'x')
            dir_name_file.close()
            dir_name_file = open(filename, 'w')
        except Exception as error:
            print(error)
        encrypted_dir_name = json.dumps({'iv':data[0], 'ciphertext':data[1], 'type':"directory"})
        dir_name_file.write(encrypted_dir_name)

        # rename directory
        os.rename(dir_list[real_i][1], new_path)
    return

# call the encrypt functions
recursive_encryption(Name, os.getcwd())

if(encrypt_dir_name):
    directory_encryption()
    dir_counter = len(dir_list)
else:
    dir_counter = 0


# output some stats
if(dir_counter == 0 and file_counter == 0):
    print('\n0 files and directories encrypted.')
    print('Are u sure the file / directory u tried to encrypt exists?')
elif(dir_counter == 1 and file_counter == 0):
    print('\n' '1 directory is successfully encrypted')
elif(dir_counter == 0 and file_counter == 1):
    print('\n' '1 file is successfully encrypted')
elif(dir_counter == 1 and file_counter == 1):
    print('\n' '1 file and 1 directory are successfully encrypted')
elif(dir_counter > 1 and file_counter == 0):
    print('\n' + "{}".format(file_counter) +  ' directories are successfully encrypted')
elif(dir_counter == 0 and file_counter > 1):
    print('\n' + "{}".format(file_counter) + ' files are successfully encrypted')
else:
    print('\n' + "{}".format(file_counter) + ' files and ' + "{}".format(dir_counter) +  ' directories are successfully encrypted')
